quotes/urls.py
from django.urls import path

from . import views


app_name = "quotes"
urlpatterns = [
        path("", views.index, name="index"),
        path("detail/", views.detail, name="detail"),
        path("results/", views.results, name="results"),
]

randomquotesapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("quotes.urls")),
    path("quotes/", include("quotes.urls")),
    path("admin/", admin.site.urls),
]

quotes/models.py
from django.db import models


class QuoteCategory(models.Model):
    category = models.CharField(max_length=50, unique=True)

    def __str__(self) -> str:
        return self.category


class Quote(models.Model):
    category = models.ForeignKey('QuoteCategory', on_delete=models.PROTECT, default=1)
    quote_text = models.CharField(max_length=900)
    quote_author = models.CharField(max_length=50)
    quote_year = models.IntegerField()
    pub_date = models.DateTimeField("date published")

    def __str__(self) -> str:
        return self.quote_text

quotes/views.py
from django.shortcuts import render, get_object_or_404
from .models import Quote, QuoteCategory

import random


# Get count of objects in DB for index page
def index(request):
    quote_count = Quote.objects.order_by("pub_date").count()
    context = {
        "quote_count": quote_count,
    }
    return render(request, "quotes/index.html", context)


# Get count of objects in DB for details page
def detail(request):
    quote_count = Quote.objects.order_by("pub_date").count()
    context = {
        "quote_count": quote_count,
    }
    return render(request, "quotes/detail.html", context)


# Get all objects from DB and make random choice to dispaly random quote on results page
def results(request):

    # Get the chosen category
    quote_category = request.GET.get('category')

    if quote_category:
        category = get_object_or_404(QuoteCategory, category=quote_category)
        quote_list = list(Quote.objects.filter(category=category))
    else:
        quote_list = list(Quote.objects.all())

    # Generate the random quote from the specified category
    if quote_list:
        random_quote = random.choice(quote_list)
        author = random_quote.quote_author
        year = random_quote.quote_year
    else:
        random_quote = None
        author = None
        year = None

    img = [
            "../../static/images/background-images/img-1.jpg",
            "../../static/images/background-images/img-2.jpg",
            "../../static/images/background-images/img-3.jpg",
            "../../static/images/background-images/img-4.jpg",
            "../../static/images/background-images/img-5.jpg",
            "../../static/images/background-images/img-6.jpg",
            ]
    rdm_choice = random.randint(0, 5)
    bg_img = img[rdm_choice]

    context = {
        "random_quote": random_quote,
        "author": author,
        "year": year,
        "background": bg_img,
        "quote_category": quote_category,
    }

    return render(request, "quotes/results.html", context)

quotes/templates/base/main.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">

    <head>
        <title>Citations Aléatoires</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    </head>

    <body>
        <div class="container">
            <div class="content-wrap">
                {% include "header.html" %}
                {% block template %}
                {% endblock %}
            </div>

            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        </div>

        {% include "footer.html" %}
        <script type="text/javascript" src=" {% static 'scripts/animation.js' %}"></script>
        <script type="text/javascript" src="{% static 'scripts/transition.js' %}"></script>
    </body>

</html>

quotes/templates/footer.html
<footer id="footer">
    <p>Copyright &copy; {% now "Y" %} <strong>DWD Numérique</strong>. All Rights Reserved.</p>
</footer>

quotes/templates/header.html
<div>
    <h1 class="col-xs-1 text-center">
        <a id="header-text" href="{% url 'quotes:index' %}">Citations aléatoires</a>
    </h1>
</div>

quotes/templates/quotes/detail.html
{% extends "../base/main.html" %}

{% block template %}
    <container class="detail-page-container">
        <h2 class="col-xs-1 text-center">Choississez une catégorie de citation</h2>


        {% if quote_count > 0 %}

            <div class="cat-selection">
                <a class="btn-cat-selection" href="{% url 'quotes:results' %}?category=Politique">Politique</a>
                <a class="btn-cat-selection" href="{% url 'quotes:results' %}?category=Inspirationnel">Inspirationnel</a>
                <a class="btn-cat-selection" href="{% url 'quotes:results' %}?category=Film">Film</a>
                <a class="btn-cat-selection" href="{% url 'quotes:results' %}?category=Humour">Humour</a>
            </div>

            <h2 class="col-xs-1 text-center">Sinon générez une citation aléatoire peux importe la catégorie</h2>
            <a class="btn col-xl-2" id="random-choice" href="{% url 'quotes:results' %}">Aléatoire</a>

            <div class="nav-btn">
                <a class="btn-return" href="{% url 'quotes:index' %}"><< Retour</a>
            </div>

        {% else %}
            <p> Il n'y a pas de citations disponible actuellement.</p>
        {% endif %}
    </container>

{% endblock %}

quotes/templates/quotes/index.html
{% extends "../base/main.html" %}

{% block template %}
    <div class="homepage-container">
        <h2 class="col-xs-1 text-center">Bonjour, bienvenu sur l'appli de citations connues.</h2>

        
        {% if quote_count > 0 %}

        <h2 class="col-xs-1 text-center">Nous avons actuellement {{ quote_count }} citatations dans notre base de données</h2>

        <p class="col-xs-1 text-center">Cliquez sur le boutton ci-dessous pour accéder aux catégories de citations</p>

        <a class="btn col-xl-2" id= "btn-animation" href="{% url 'quotes:detail' %}">Choix de catégorie</a>

        {% else %}
            <p> Il n'y a pas de citations disponible actuellement.</p>
        {% endif %}
    </div>

{% endblock %}

quotes/templates/quotes/results.html
{% extends "../base/main.html" %}

{% block template %}
    <container class="results-page-container">
        <div class="quote-result-page" style="background-image: url( '{{ background }}')">
            <div class="container-fluid">
                <div class="col align-self-center quote-result">
                    <div id="quote">
                        <p>" {{ random_quote }} "</p>
                    </div>

                    <div id="quote-detail">
                        {% if author == "Inconnu" and year < 1 %}
                            <p> Auteur Inconnu - Année Inconnu</p>
                        {% elif author == "Inconnu" and year > 0 %}
                            <p>Auteur Inconnu - {{ year }}</p>
                        {% elif author != "Inconnu" and year < 1 %}
                            <p>{{ author }} - Année Inconnu</p>
                        {% else %}
                            <p>{{ author }} - {{ year }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="result-cat-selection">
            <a class="btn-result-cat-selection" href="{% url 'quotes:results' %}?category=Politique">Politique</a>
            <a class="btn-result-cat-selection" href="{% url 'quotes:results' %}?category=Inspirationnel">Inspirationnel</a>
            <a class="btn-result-cat-selection" href="{% url 'quotes:results' %}?category=Film">Film</a>
            <a class="btn-result-cat-selection" href="{% url 'quotes:results' %}?category=Humour">Humour</a>
            <a class="btn-result-cat-selection" href="{% url 'quotes:results' %}">Tous</a>
        </div>

        <div class="nav-btn">
            <a class="btn-home" href="{% url 'quotes:index' %}">Acceuil</a>
            <a class="btn-return" href="{% url 'quotes:detail' %}"><< Retour</a>
        </div>
    </container>

{% endblock %}